# Generated by Django 5.2.4 on 2025-07-27 10:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("tin", models.CharField(max_length=255, unique=True)),
                ("phone", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("address", models.TextField()),
                ("nic_or_passport", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
